Merge Card component
piyushsh25/enginUI pull request #5
Opened 2022-02-03 10:04 UTC by piyushsh25

![Screenshot (189)](https://user-images.githubusercontent.com/72690317/152321356-f4c2a601-a3b1-4fc6-84c0-9f6b433fb947.png)

2022-02-03 11:19 UTC, RakshithBhat03 requested changes

2022-02-03 11:19 UTC, RakshithBhat03 commented on components/card/card.css
> +.card .upper-div img {
"upper-div" class can have a better name. Also, add a class for img tag.

2022-02-03 11:19 UTC, RakshithBhat03 commented on components/card/card.css
> +.lower-div {
This class can have a better name

2022-02-03 11:19 UTC, RakshithBhat03 commented on components/card/card.css
> +.card .lower-div li {
"li" tag can also have class of its own.

2022-02-03 11:19 UTC, RakshithBhat03 commented on components/card/card.css
> +.card .lower-div li.text-icon {
No need to combine these many selectors, since ".text-icon" class is being used only by "li" tag. Directly defining ".text-icon" will do fine

2022-02-03 12:36 UTC, RakshithBhat03 reviewed
Apart from these everything else looks good

2022-02-03 15:31 UTC, RakshithBhat03 reviewed
Looks good!

2022-02-04 03:37 UTC, AnuragSahu11 reviewed
You should use variables for repeated units like 5%, 20rem ,18rem, and also text-overlay-card is more descriptive name than text-over-card. Other than that everything looks good.

2022-02-04 04:52 UTC, merged